'use strict';

angular.module('phosphoApp')
  .constant('demoPathways', {
    'titles':[
      'DLBCL'
    ],
    'pathways': [
      {'DLBCL':{
        'graph':{
          'nodes':[
            {
              'id':0,
              'Label':'BCR',
              'Type':'prot'
            },
            {
              'id':1,
              'Label':'PIK3CD',
              'Type':'prot'
            },
            {
              'id':2,
              'Label':'PIK3R1',
              'Type':'prot'
            },
            {
              'id':3,
              'Label':'Cell Growth',
              'Type':'event'
            },
            {
              'id':4,
              'Label':'LYN',
              'Type':'prot'
            },
            {
              'id':5,
              'Label':'CD79',
              'Type':'prot'
            },
            {
              'id':6,
              'Label':'SYK',
              'Type':'prot'
            },
            {
              'id':7,
              'Label':'IRAK4',
              'Type':'prot'
            },
            {
              'id':8,
              'Label':'BCL6',
              'Type':'prot'
            },
            {
              'id':9,
              'Label':'NFKB Path',
              'Type':'Path'
            },
            {
              'id':10,
              'Label':'Ca2+ Rel',
              'Type':'event'
            },
            {
              'id':11,
              'Label':'BTK',
              'Type':'prot'
            },
            {
              'id':12,
              'Label':'CARD11',
              'Type':'prot'
            },
            {
              'id':13,
              'Label':'JAK2',
              'Type':'prot'
            },
            {
              'id':14,
              'Label':'STAT3',
              'Type':'prot'
            },
            {
              'id':15,
              'Label':'Cell Survival',
              'Type':'event'
            }
          ],
          'links':[
            {
              'source':0,
              'target':1,
              'Type':'activate'
            },
            {
              'source':1,
              'target':2,
              'Type':'activate'
            },
            {
              'source':2,
              'target':3,
              'Type':'activate'
            },
            {
              'source':4,
              'target':0,
              'Type':'inhibit'
            },
            {
              'source':4,
              'target':5,
              'Type':'inhibit'
            },
            {
              'source':4,
              'target':6,
              'Type':'activate'
            },
            {
              'source':6,
              'target':11,
              'Type':'activate'
            },
            {
              'source':11,
              'target':10,
              'Type':'activate'
            },
            {
              'source':10,
              'target':12,
              'Type':'activate'
            },
            {
              'source':12,
              'target':9,
              'Type':'activate'
            },
            {
              'source':13,
              'target':14,
              'Type':'activate'
            },
            {
              'source':14,
              'target':15,
              'Type':'activate'
            },
            {
              'source':7,
              'target':9,
              'Type':'activate'
            },
            {
              'source':8,
              'target':3,
              'Type':'activate'
            },
            {
              'source':9,
              'target':15,
              'Type':'activate'
            },
            {
              'source':9,
              'target':3,
              'Type':'activate'
            }
          ],
          'metadata':{
            'author':'Phospho',
            'title':'DLBCL'
          }
        }
      }
    }
    ]
  });
